# Generated by Django 3.1.6 on 2021-02-12 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3, verbose_name='Номер группы')),
                ('faculty', models.CharField(max_length=30, verbose_name='Название факультета или цифра')),
                ('course', models.CharField(max_length=1, verbose_name='Курс обучения, цифра')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя студента')),
                ('surname', models.CharField(max_length=3, verbose_name='Фамилия')),
                ('fathersname', models.CharField(max_length=3, verbose_name='Отчество')),
                ('date', models.DateTimeField(max_length=3, verbose_name='Дата рождения')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.group', verbose_name='Номер группы')),
            ],
        ),
    ]
