# Generated by Django 3.1.6 on 2021-02-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210212_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.CharField(max_length=1, verbose_name='Курс обучения (цифра)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='faculty',
            field=models.CharField(max_length=2, verbose_name='Номер факультета (цифра)'),
        ),
    ]
